apiVersion: v1
kind: ConfigMap
metadata:
  name: tracerbullet-config
data:
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
           return 200 "{{ tpl .Values.message $ }}";
       }
   }
}
'
